### ISSUE TITLE
next.js update to 12v - building crashed

### ISSUE THREAD

**Issue by Zhanadil1509** [preactjs/next-plugin-preact#60] opened 2022-05-11 10:55 UTC
Error: Cannot find module 'react-dom/server.browser'
Require stack:
- /home/projects/nextjs-preact-webpack5-t2s3fm/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (https://nextjs-preact-webpack5-t2s3fm.w.staticblitz.com/blitz.1becece65fb9e6d89d27bbe87eedd4d64b37a3a4.js:6:217231)
    
    https://stackblitz.com/edit/nextjs-preact-webpack5-t2s3fm?file=package.json

**Comment by thevinter** [comment] 2022-05-16 14:30
Can confirm this is happening to me as well

**Comment by amursky** [comment] 2022-05-17 12:10
+1

**Comment by aleppos** [comment] 2022-05-18 17:18
+1

**Comment by cheeplusplus** [comment] 2022-05-20 08:32
This was caused by upstream and appears to have been fixed in https://github.com/vercel/next.js/pull/36749

**Comment by nurliman** [comment] 2022-05-21 07:11
so what do we do now?

**Comment by cheeplusplus** [comment] 2022-05-21 07:12
use an earlier version? or run canary until the next full version is released

**Comment by lfre** [comment] 2022-06-06 21:43
This is fixed in the latest (17.1.1) [@preact/compat](https://www.npmjs.com/package/@preact/compat) for Next 12.1.6.

**Closed** 2022-06-07 09:24 UTC
